---
title: "Text Based Occupation Classification"
format: gfm
---

## Introduction

This repo holds a classification method for classifying occupational strings to a set of different schemas.

This is part of my PhD project on technological change in Sweden in the 20th century.

This is ongoing work and the code is not yet finished, check back later.

## Planning

The approach to classify occupations as recorded in biographical dictionaries is relatively simple.

We have a schema of occupations grouped into different sectors. Each occupation has a description of the tasks and duties involved with the occupation. One popular schema is HISCO. Another is ISCO. We take these titles and descriptions and project them into a vector space using a text embedding model (sentence and word - we need to see which works better). 

Then we take the occupational strings and use the same text embedding model to project them into a vector space. 

To classify the occupational strings according to the schema, we calculate the distance between the string and it's closest occupation in the schema from the schema. We set some threshold whereby it is deemed a close enough match, and classify the string as that occupation.

## Data

We are gathering schemas from HISCO and ISCO to begin with at different levels of specificity.

For example, a HISCO code can be 5 digits long. 

## Assign HISCOs: process

```{mermaid}
graph TB
    A[Collect HISCO Codes<br>and Descriptions] -->|Use OpenAI API| B[Convert HISCO Titles<br>and Descriptions to Vectors]
    C[Receive Occupational<br>Strings] -->|Use OpenAI API| D[Convert Occupational<br>Strings to Vectors]
    B --> E[Compare Vectors in<br>Vector Space]
    D --> E
    E --> F[Assign HISCO Code to<br>Occupational String<br>using Cosine Distance]
    style A fill:#2B8CBE
    style B fill:#be5d2b
    style C fill:#2B8CBE
    style D fill:#be5d2b
    style E fill:#6f6fbf
    style F fill:#F4FA58


```


## Classifcation training data

Job tech adverts [here](https://data.jobtechdev.se/annonser/jobtechlinks/index.html) provide job adverts and they have coded up ssyk occupational codes at 4 digit level. 

I am not 100% sure that their classification is good?

For example, they give "Frukostvärd/Frukostvärdinna" code 5120, which is 

    {
        "code": "5120",
        "title": "Kockar och kallskänkor ",
        "level": 4,
        "description": "Lagar, lägger upp och garnerar mat inom hotell- och restaurangnäring, inom storkök, provkök, på ett fartyg eller i en butik. Yrkesgrupp"
    },

Maybe this one is better?

9412 Restaurang- och köksbiträden m.fl.
Portionerar mat, tar emot betalning i kassa samt plockar disk och diskar inom restaurang eller storkök. Förbereder mat, sköljer, skalar och hackar grönsaker. Deltar i enklare matlagning. Ansvarar för frukostservering.

9412 Restaurant and kitchen assistants, etc.
Portions food, accepts payment at the till and picks dishes and dishes within a restaurant or commercial kitchen. Prepares food, rinses, peels and chops vegetables. Participates in simple cooking. Responsible for serving breakfast.

Another one that looks wrong:

        "title": "\"The future depends on what you do today – Join ALTEN Life Science\"",
        "@context": "http://schema.org/",
        "relevantOccupation": {
            "@type": "Occupation",
            "name": "Biomedicinare",
            "occupationalCategory": {

classified as         "code": "2144",
        "title": "Civilingenjörsyrken inom maskinteknik",


Another mistake:

    {
        "job_title": "Kranbilsf\u00f6rare",
        "ssyk_lvl4": 9412
    },

9412 is cook in a restaurant not a crane operator. 


Is this correct?

## What is doing well?

Need to create a scoring method - top-n classification seems reasonable.

